### ISSUE TITLE
documentation for building, usage

### ISSUE THREAD

**Issue by matthargett** [arter97/linaro-lto#1]
Hi,
I'm very interested to reproduce a working LTO-compiled kernel for my Kindle 2/3 project. Can you provide some minimal documentation on:
1. bootstrapping the toolchain, either manually or via ct-ng
2. what kernel source you used, or patchset you apply to vanilla/Android/Linaro kernels
bonus: kernel size savings and noteworthy performance improvements, if any, on hardware you tested on

Great work, looking forward to seeing more great stuff!

**Comment by arter97** [comment]
1. I use prebuilt Linaro toolchain directly from Linaro and build
   binutils-hg(old version) by myself. Commits from this Git repo explains it
   well.
   I personally had failures with LTO on latest binutils-hg, that's why I'm
   using an old version.
2. Android kernels. Galaxy S4(GT-i9506, 3.4), Nexus 7(flo, 3.4), LG G
   Watch(dory, 3.10).
   https://bitbucket.org/arter97/android_kernel_samsung_msm8974/commits/all?search=LTO
   https://bitbucket.org/arter97/android_kernel_asus_flo/commits/all?search=LTO
   https://bitbucket.org/arter97/android_kernel_lge_dory/commits/all?search=LTO
   Yes, I observed some size reduction(few hundreds of kilobytes), but not
   performance improvements. Also note that I failed to make kernel modules
   working with my LTO ports, which is not really an issue since none of my
   devices use kernel modules.
   I don't use LTO with my current daily driver, Galaxy S6(SM-G920F, 3.10,
   Aarch64), because
   A. I'm limited to old version of binutils but I really wanted the latest
   one.
   B. Can't observe real performance benefits.
   C. I'm not capable of finding any code compilation durps, which can
   potentially alternate code, with LTO.  Thus I consider it dangerous.

**Comment by matthargett** [comment]
thanks for answering so quickly! :)

Turning off modules and building with LTO allows for better optimization/dead code elimination anyway, eliminating (or optimizing for size) many code paths only used by certain modules. In my experience with LTO kernels, network communications over loopback interface sees sees lower CPU usage and some syscalls are optimized away due to better inlining.

Does the old version of binutils not work better with LTO when using -fuse-linker-plugin during compile/link? You need to configure binutils to --enable-plugins, then configure the toolchain to do the same _with the same plugins-enabled binutils_. It's easy to miss a step and end up with an even more flaky LTO experience than normal.

In rebuilding core Kindle libraries and programs with Linaro GCC 5.2 and LTO -Os, some binaries are literally half the size (JavaScriptCore stripped goes from 4+MB to ~2MB) while still being 2x-8x faster in key benchmarks than the original binaries that were mostly compiled with GCC 4.1 with -Os.

**Comment by arter97** [comment]
What I meant by old binutils-hg is the one still able to link LTO with ARM
kernels and yes, it uses -fuse-linker-plugin.
I'm very much aware of this process(cause I've been trying to port andi's
LTO to my Android device for over a year) including configuring binutils
with --enable-plugins. What is weird is old binutils-hg works but latest
binutils-hg gives linking error.
Since old binutils-hg works, I figured I don't have to recompile the GCC.
I've explained my case in the comments here :
https://github.com/andikleen/linux-misc/commit/664de370c2f8f3ae4468ce1e6ed7c80884019c17

LTO -Os, isn't LTO -O3(or -Ofast, if that's fine) much better?

Btw, why are you asking me this lol
You seems to be more expert on this :)

**Comment by matthargett** [comment]
I've never gotten kernel LTO to work on ARM, but have used it very successfully on userland ARM and kernel x86 with GCC 4.9 and 5.x. in GCC 5.x, the compiler is now smart enough to speculatively inline during -Os and figure out if the inline will ultimately result in smaller/same size code. More "small" inlining then happens with LTO -Os, with incredibly smaller binary sizes than -O2. 

My current focus is on getting the binaries to be as small as possible without awful performance so that there is more free physical RAM on Kindle 2/3, which only have 64 or 128MB of RAM. In my experiments, I have seen that sometimes -O3/Ofast LTO binaries are actually smaller than -O2 LTO binaries (ipa-cp-clone being a primary reason). My primary benchmarks for this are JavaScriptCore and v8.

Since your primary target has 10x more RAM and 10x faster CPU, the binary size reductions (userland and kernel) and elimination of syscalls (kernel) may be noise. On a 200mhz ARMv6j device with 64MB of RAM, it allows for enabling more browser features and loading larger "mobile" web pages that iOS 5.x+/Android 3.x+ users currently get. For instance, saving 2MB on RSS size in the JavaScriptCore binary allowed loading of "mobile" Twitter while masquerading as iPad 1 iOS 5.x -- a page which previously crashed.

Thanks for the information, keep up the interesting work! :)

**Comment by arter97** [comment]
I've gave my Galaxy S6 another shot.
https://bitbucket.org/arter97/android_kernel_samsung_exynos7420/commits/branch/lto

Seems like it's building well with new binutils-hg.
Trick was that I needed to use gcc-ld as the linker.

I was quite surprised by how much LTO have gotten faster with GCC 5.2 +
latest binutils-hg.

Non-LTO build is 1m 8s,
LTO build is 1m 30s.

Not bad :)

Image does load, but it panics on 0.8s with driver initialization
failure(page fault).

Moar digging.. :D

**Comment by ijinma** [comment]
@arter97 
hi, I have just started to learn the kernel. I am very interested in the LTO kernel at present and want to use LTO to compile the kernel on ARM. 

In [kernel-lto.pdf](http://halobates.de/kernel-lto.pdf), I see "tested on X86, arm, MIPs" and "branch lto-3. X", but I see "only tested on X86 for now." in branch lto-3. X. It seems that ARM is not supported. 

In [Microsoft-Exploring-PGO-Linux](https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-Exploring-PGO-Linux), I see that Microsoft seems to have succeeded, but I haven't found the relevant kernel code or relevant documents. 

I have tested the clang LTO kernel of Sami. [The results](https://github.com/samitolvanen/linux/commit/39c19542a337a34455cc81c63a49d7d039d58635#commitcomment-44890247) show that there is almost no benefit, especially in terms of size. Most importantly, I'm not interested in CLANG LTO, just want to study GCC LTO.

I've been tossing around for weeks, and fortunately I've seen your work that you seem to have done an [LTO kernel based on an ARM machine](https://github.com/andikleen/linux-misc/issues/11), but I'm a little unfamiliar with the kernel, so I've been searching your git repository for a long time and I can't find any relevant content. 

So could your give me some help for this?  It would be great if you could provide the ARM-based LTO kernel source code or some related LTO patches. 

thank you!
